/**
 * Handoff store port.
 *
 * Stores canonical structured handoff records plus a cached UKI transfer
 * string for direct agent pickup.
 *
 * Records are identified by a `YYYY-MM-DD-NNN` id generated by
 * `generateHandoffId()` in `src/domain/id.ts`.
 */
import type {
  CreateUkiHandoffInput,
  UkiHandoff,
  UkiHandoffStatus,
} from "../domain/uki-types.js";

export interface UpdateHandoffStatusMeta {
  readonly pickedUpBy?: string;
  readonly completedAt?: string;
  readonly report?: string;
}

export interface HandoffStorePort {
  /** Create a new handoff. Generates a new id and caches the rendered UKI. */
  create(input: CreateUkiHandoffInput): Promise<UkiHandoff>;

  /**
   * Atomically claim a pending handoff, either by explicit id or by picking the
   * newest pending handoff. Returns the updated handoff, or undefined when the
   * requested handoff does not exist or is no longer pending.
   */
  claimPending(id?: string, pickedUpBy?: string): Promise<UkiHandoff | undefined>;

  /** Retrieve a handoff by id, or undefined if not found. */
  get(id: string): Promise<UkiHandoff | undefined>;

  /**
   * Return the most recent pending handoff (highest id by descending sort),
   * or undefined if none exists.
   */
  getLatestPending(): Promise<UkiHandoff | undefined>;

  /**
   * List all handoffs, optionally filtered by status. Sorted by id
   * descending (newest first).
   */
  list(filter?: { status?: UkiHandoffStatus }): Promise<readonly UkiHandoff[]>;

  /**
   * Return the most recent handoffs for a mission/feature pair, newest first.
   * Implementations may short-circuit once `limit` matches have been found.
   */
  listRecentByFeatureRefs?(
    missionId: string,
    featureId: string,
    limit: number,
  ): Promise<readonly UkiHandoff[]>;

  /**
   * Transition a handoff's status and optionally set related metadata
   * (pickedUpBy on `picked-up`, completedAt + report on `completed`).
   * Returns the updated record, or undefined if the id was not found.
   */
  updateStatus(
    id: string,
    status: UkiHandoffStatus,
    meta?: UpdateHandoffStatusMeta,
  ): Promise<UkiHandoff | undefined>;

  /** Delete a handoff by id. Returns true if removed, false if not found. */
  delete(id: string): Promise<boolean>;
}
