name: 'Setup git-cliff'
description: 'Install git-cliff for changelog generation'

inputs:
  version:
    description: 'git-cliff version to install'
    required: false
    default: '2.7.0'

runs:
  using: 'composite'
  steps:
    - name: Install git-cliff
      shell: bash
      run: |
        set -euo pipefail

        VERSION="${{ inputs.version }}"
        ARCHIVE="git-cliff-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        URL="https://github.com/orhun/git-cliff/releases/download/v${VERSION}/${ARCHIVE}"

        echo "Installing git-cliff v${VERSION}..."
        curl -sSfL "$URL" | tar xz
        sudo mv "git-cliff-${VERSION}/git-cliff" /usr/local/bin/

        echo "Installed git-cliff $(git-cliff --version)"
