pub mod decisions;
pub mod domain;
pub mod evidence;
pub mod feature;
pub mod foundation;
pub mod harness;
pub mod improver;
pub mod install;
pub mod interfaces;
pub mod metrics;
pub mod migrate;
pub mod operations;
pub mod skills;
pub mod task;
pub mod update;
pub mod verification;

pub use foundation::core;
pub use interfaces::cli as commands;
pub use interfaces::hooks;
pub use interfaces::mcp;
pub use interfaces::shell;
pub use interfaces::tui;
