pub mod decisions;
pub mod domain;
pub mod evidence;
pub mod feature;
pub mod foundation;
pub mod harness;
pub mod hooks;
pub mod improver;
pub mod install;
pub mod interfaces;
pub mod mcp;
pub mod metrics;
pub mod migrate;
pub mod operations;
pub mod skills;
pub mod task;
pub mod tui;
pub mod update;
pub mod verification;

pub use foundation::core;
pub use interfaces::cli as commands;
pub use interfaces::shell;
